theme: jekyll-theme-minimal
title: llmauto
description: Bookmark this to keep an eye on my project updates!

# Blog configuration
permalink: /:year/:month/:day/:title/

# Optional: Add navigation
plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-sitemap

# Enable relative links processing
relative_links:
  enabled: true
  collections: true